name: "MergeBase"
description: "Scan your repositories with MergeBase!"
author: "Delan Elliot"
branding:
  icon: "alert-triangle"
  color: "red"
inputs:
  project_name:
    description: "name of your MB project"
  mb_token:
    description: "Customer token from your MB dashboard"
  mb_url:
    description: "Your dashboard URL in the form https://[domain].mergebase.com"
  additional_args:
    description: "additional command line arguments. See CLT user guide for list of available options"
    default: ""
runs:
  using: "docker"
  image: "docker://mergebase/mergebase-sca-base" 
  env:
    MB_ENV: GITHUB_ACTION
  args:
  - java -Dmb.url=${{inputs.mb_url}} -Dmb.token=${{inputs.mb_token}} -jar /opt/mbjar/meregbase.jar --name=${{inputs.project_name}} ${{inputs.additional_args}} . 
